metadata:
  id: 600-$UUID
  labels:
    omni.sidero.dev/machine: $UUID
  namespace: default
  type: ConfigPatches.omni.sidero.dev
spec:
  data: |-
    machine:
      nodeLabels:
        etsmtl.club/external-network: "$HAS_PUBLIC_IP"
        etsmtl.club/internal-network: "true"
      kubelet:
        nodeIP:
          validSubnets:
          - $NETWORK_CONFIG_SUBNET
      network:
        hostname: "$NAME-$ROLE-$KEY.$DOMAIN"
        disableSearchDomain: true
        nameservers: ["1.1.1.1", "1.0.0.1"]
        interfaces:
          - deviceSelector:
              hardwareAddr: $INTERNAL_INTERFACE_MAC
            dhcp: false
          - deviceSelector:
              hardwareAddr: $INTERNAL_SERVICES_INTERFACE_MAC
            dhcp: false
            routes:
              - network: $INTERNAL_SERVICES_SUBNET
          - deviceSelector:
              hardwareAddr: $CLUSTER_INTERFACE_MAC
            dhcp: false
            addresses:
              - $IP
            routes:
              - network: $NETWORK_CONFIG_SUBNET
              - network: 0.0.0.0/0
                gateway: $GATEWAY
---
metadata:
  id: $UUID
  labels:
    cluster-candidate: $NAME
    role: $ROLE
  namespace: default
  type: MachineLabels.omni.sidero.dev
spec: {}
